### ISSUE TITLE
可以支持多个fbx导入吗

### ISSUE THREAD

**Issue by throne-developer** [Larry955/FbxParser#1]
hi，我有2个fbx，可以同时显示吗？

**Comment by Larry955** [comment]
> hi，我有2个fbx，可以同时显示吗？

目前还不可以哦，我没做这块，你可以开个分支改下代码，把每个导入的fbx实例化为类的对象

我当时没做这块主要有两个问题：1）不同fbx文件的大小不一样，有的很大，有的很小，放一起显示会很不和谐；2）场景的环境初始化和模型的导入这两个模块的代码耦合性太高，再导入模型可能会把部分环境设置初始化两遍，可能会导致整个场景都出问题

要解决上述问题，需要考虑：1）将不同大小的模型归一化为同一大小；2）重构代码，将场景初始化和模型导入的代码完全分离。这两部分其实挺麻烦的，当时赶时间，就没考虑那么多了
